# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 15:41
from __future__ import unicode_literals

import actividades.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='imagen',
            field=models.ImageField(null=True, upload_to=actividades.models.directorio_imagen),
        ),
    ]
