# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_actividad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
