# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-23 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapago',
            name='tipo',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
