# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_efectivo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('num_recibo', models.IntegerField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Actividad')),
                ('forma_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movimientos.FormaPago')),
            ],
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='forma_pago',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
