# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 21:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
        ('clientes', '0003_auto_20180929_1832'),
        ('movimientos', '0002_auto_20180929_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='actividad',
        ),
        migrations.AddField(
            model_name='recibo',
            name='actividad',
            field=models.ManyToManyField(to='actividades.Actividad'),
        ),
    ]
