# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='tipo',
            field=models.CharField(choices=[('FJ', 'Fijo'), ('MV', 'Celular')], default='MV', max_length=2),
        ),
    ]
